---
title: Pythonのsleep（スリープ）コマンドを使う
hero_image: images/banner.png
description: sleep（スリープ）コマンドでPythonプログラムを一時的に止める方法を学ぶ
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "python"
site_areas:
steps:
  - 
    title: はじめに
